### ISSUE TITLE
1.18.2forge加载R5 mod报错

### ISSUE THREAD

**Issue by buggzd** [AmarokIce/WithThursdays#1]
[minecraft-exported-crash-info-2022-12-05T18-10-00.zip](https://github.com/AmarokIce/WithThursdays/files/10153063/minecraft-exported-crash-info-2022-12-05T18-10-00.zip)
错误日志已上传

**Comment by AmarokIce** [comment]
早上好！
感谢反馈！已经解决！
经检查发现是toml文件出现问题，mcmod中已经上传FIX版本，也亦可从其他模组中获取一份toml拷贝并修改modid塞进去解决
CurseForge会稍晚些上传
